$hider = 1500;
$shower = 230;
$showerz = '9999';
$hiderz  ='1';
$bgcolor = "#44bbff";
$transparent = "";
$( document ).ready(function() {
	$('#links1').css({'background-color': $bgcolor});
	$('#homeconatainer').css({'z-index': $showerz});
	$('#productconatainer').css({'z-index': $hiderz});
	$('#messagecontainer').css({'z-index': $hiderz});
	$('#requestcontainer').css({'z-index': $hiderz});
	$('#ordercontainer').css({'z-index': $hiderz});
	$('#membercontainer').css({'z-index': $hiderz});
	$('#editwebsitecontainer').css({'z-index': $hiderz});
	$('#reportcontainer').css({'z-index': $hiderz});
	$("#homecontainer").animate({left: $shower,});
	$("#productcontainer").animate({left:$hider,});
	$("#messagecontainer").animate({left:$hider,});
	$("#requestcontainer").animate({left:$hider,});
	$("#ordercontainer").animate({left:$hider,});
	$("#membercontainer").animate({left:$hider,});
	$("#editwebsitecontainer").animate({left:$hider,});
	$("#reportcontainer").animate({left:$hider,});
	$('#links1').css({'background-color': $bgcolor});
	$('#links2').css({'background-color': $transparent});
	$('#links3').css({'background-color': $transparent});
	$('#links4').css({'background-color': $transparent});
	$('#links5').css({'background-color': $transparent});
	$('#links6').css({'background-color': $transparent});
	$('#links7').css({'background-color': $transparent});
	$('#links8').css({'background-color': $transparent});
});
