		$hider = 1500;
		$shower = 230;
		$showerz = '9999';
		$hiderz  ='1';
		$bgcolor = "#44bbff";
		//$transparent = "rgba(0,0,0,0)";
		$transparent = "";
		$( document ).ready(function() {
			$('#links1').css({'background-color': $bgcolor});
		});
		$("#links1").click(function() {
			$('#homeconatainer').css({'z-index': $showerz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $shower,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $bgcolor});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links2").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $showerz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$shower,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $bgcolor});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links3").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $showerz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$shower,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $bgcolor});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links4").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $showerz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$shower,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $bgcolor});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links5").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $showerz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$shower,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $bgcolor});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links6").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $showerz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$shower,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $bgcolor});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links7").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $showerz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$shower,});
			$("#reportcontainer").animate({left:$hider,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $bgcolor});
			$('#links8').css({'background-color': $transparent});
		});
		$("#links8").click(function() {
			$('#homeconatainer').css({'z-index': $hiderz});
			$('#productconatainer').css({'z-index': $hiderz});
			$('#messagecontainer').css({'z-index': $hiderz});
			$('#requestcontainer').css({'z-index': $hiderz});
			$('#ordercontainer').css({'z-index': $hiderz});
			$('#membercontainer').css({'z-index': $hiderz});
			$('#editwebsitecontainer').css({'z-index': $hiderz});
			$('#reportcontainer').css({'z-index': $showerz});
			$("#homecontainer").animate({left: $hider,});
			$("#productcontainer").animate({left:$hider,});
			$("#messagecontainer").animate({left:$hider,});
			$("#requestcontainer").animate({left:$hider,});
			$("#ordercontainer").animate({left:$hider,});
			$("#membercontainer").animate({left:$hider,});
			$("#editwebsitecontainer").animate({left:$hider,});
			$("#reportcontainer").animate({left:$shower,});
			$('#links1').css({'background-color': $transparent});
			$('#links2').css({'background-color': $transparent});
			$('#links3').css({'background-color': $transparent});
			$('#links4').css({'background-color': $transparent});
			$('#links5').css({'background-color': $transparent});
			$('#links6').css({'background-color': $transparent});
			$('#links7').css({'background-color': $transparent});
			$('#links8').css({'background-color': $bgcolor});
		});